scope: patroni-experiments
name: <name>

restapi:
  listen: <host>:<patroni_port>
  connect_address: <host>:<patroni_port>

etcd:
  host: <host>:<etcd_port>

bootstrap:
  dcs:
    ttl: 60
    loop_wait: 5 
    retry_timeout: 30
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      pg_hba:
      - host replication replicator <host>/32 md5
      - host replication replicator 0.0.0.0/0 md5
      - host all all 0.0.0.0/0 md5
      
  initdb:
  - encoding: UTF8
  - data-checksums

  users:
    admin:
      password: admin%
      options:
        - createrole
        - createdb

postgresql:
  listen: <host>:<pg_port>
  connect_address: <host>:<pg_port>
  data_dir: <pg_data_dir>
  pgpass: /tmp/pgpass1
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: password
    rewind:
      username: rewind_user
      password: rewind_password
  parameters:
    unix_socket_directories: '..'
    logging_collector: on
    log_directory: logs
  basebackup:
    - verbose
    - max-rate: 100M

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false

log:
  level: DEBUG
  dir: <patroni_log_dir>